name: golang-codecov

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

jobs:
  golang-codecov:
    name: golang-codecov
    strategy:
      matrix:
        go:
          - '^1.17'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go SDK
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Print env info
        run: |
          go env
          go version

      - name: Run go build
        run: go build -v ./...

      - name: Run test coverage
        run: go test -cover -coverprofile coverage.txt -covermode count -tags test -coverpkg ./... -v ./...

      - name: Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage.txt
#          verbose: true

